# Spark + Iceberg + Hive Metastore + MinIO (S3A)
spark.sql.extensions                        org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions
spark.sql.catalog.spark_catalog              org.apache.iceberg.spark.SparkSessionCatalog
spark.sql.catalog.spark_catalog.type         hive
spark.sql.catalog.spark_catalog.uri          thrift://hive-metastore:9083
spark.sql.catalog.spark_catalog.warehouse    s3a://warehouse
spark.hadoop.fs.s3a.endpoint                 http://minio:9000
spark.hadoop.fs.s3a.access.key               minioadmin
spark.hadoop.fs.s3a.secret.key               minioadmin
spark.hadoop.fs.s3a.path.style.access        true
spark.hadoop.fs.s3a.impl                     org.apache.hadoop.fs.s3a.S3AFileSystem
